import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Navbar from "@/components/Navbars/Navbar";
import BaseHeader from "@/components/BaseHeader";
import Footer from "@/components/Footer";
import { MantineProvider, createTheme } from "@mantine/core";
import InitialValidityCheck from "@/components/InitialValidityCheck";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  // weight: ["400", "500", "700"], // common weights, adjust if needed
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const theme = createTheme({
  fontSizes: { md: "14px", sm: "13px", xs: "12px" },
  components: {
    TagsInput: {
      styles: {
        input: { fontSize: 14, minHeight: 36 },
        root: { width: "100%" },
      },
    },
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${roboto.variable}`}
    >
      <body className="antialiased">
        <MantineProvider theme={theme}>
          <ReduxProvider>
            <InitialValidityCheck>
              <BaseHeader />
              <Navbar />
              {children}
              <Footer />
            </InitialValidityCheck>
          </ReduxProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
