import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { SidebarProvider } from "@/components/Sidebar/Sidebar";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  // weight: ["400", "500", "700"], // common weights, adjust if needed
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${roboto.variable}`}>
      <body className="antialiased min-h-[100svh]">
        <SidebarProvider>
          <div className="fixed top-0 left-0 h-[100svh] z-40">
            <Sidebar />
          </div>
          <main className="pt-8 lg:pt-0 bg-gray-100 lg:ml-[227px] xl:ml-[300px] min-h-[100svh]">
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
